spring:
    profiles:
        active:
        - dev
---
spring:
    profiles: dev  #开发环境
    application:
        name: microservicecloud-config-wuzhijing-dev
---
spring:
    profiles: test  #测试环境
    application:
        name: microservicecloud-config-wuzhijing-test
#请注意保存成utf-8形式